<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.AspNetCore.Http.Validation.Generated</InterceptorsNamespaces>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Azure.Communication.Email" Version="1.1.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.ApiDescription.Server" Version="10.0.11">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
        <PackageReference Include="Npgsql.OpenTelemetry" Version="10.0.3" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.17.0" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.17.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.17.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.17.0-beta.1" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.17.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.17.0" />
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="Serilog.Sinks.OpenTelemetry" Version="4.2.0" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Prezentownik.WebApi.Tests" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Resources\IdentityErrors.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>LocalizedIdentityErrorDescriber.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\IdentityErrors.pl.resx">
        <DependentUpon>IdentityErrors.resx</DependentUpon>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Resources\IdentityErrors.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>IdentityErrors.resx</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
